name: Welcome Home Pipeline

on:
  schedule:
    # Run daily at 2:00 AM EST (7:00 AM UTC)
    - cron: '0 7 * * *'
  workflow_dispatch:
    # Allow manual triggering with optional table selection
    inputs:
      tables:
        description: 'Comma-separated list of tables to process (e.g., Prospects,Activities). Leave empty for all.'
        required: false
        type: string
        default: ''

jobs:
  process-table:
    # The 'if' condition was removed from here.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        table: [
          "Organizations",
          "Referrers", 
          "Influencers",
          "Units",
          "HousingContracts",
          "DepositTransactions",
          "MarketingTouchpoints",
          "ServiceAgreements",
          "Traits",
          "Prospects",
          "Residents",
          "Activities"
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process table ${{ matrix.table }}
        if: ${{ github.event.inputs.tables == '' || contains(github.event.inputs.tables, matrix.table) }}
        env:
          WELCOME_HOME_API_KEY: ${{ secrets.WELCOME_HOME_API_KEY }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          python main.py ${{ matrix.table }}

      - name: Upload logs for ${{ matrix.table }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs-${{ matrix.table }}
          path: welcome_home_pipeline_*.log
          retention-days: 7
